version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - bgrainger
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  assignees:
  - bgrainger
